# Generated by Django 5.2.5 on 2025-08-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_from_ozon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_art_from_ozon', models.CharField(max_length=255, verbose_name='Артикул товара с Ozon')),
                ('price_with_discount_ozon', models.IntegerField(blank=True, null=True, verbose_name='Цена с учетом скидки от кошелька')),
                ('price_ozon_s_be', models.IntegerField(blank=True, null=True, verbose_name='Цена, которая должна быть на Ozon')),
                ('price_with_co_invest', models.IntegerField(blank=True, null=True, verbose_name='Цена с соинвестом')),
                ('price_without_co_invest', models.IntegerField(blank=True, null=True, verbose_name='Цена без соинвеста')),
                ('discount_co_invest', models.FloatField(blank=True, null=True, verbose_name='Скидка соинвеста')),
                ('discount_ozon_with_wallet', models.FloatField(blank=True, null=True, verbose_name='Скидка кошелька Ozon')),
                ('price_ozon_s_be_with_wallet', models.IntegerField(blank=True, null=True, verbose_name='Цена, которая должна быть с учетом скидки кошелька Ozon')),
                ('price_ozon_s_be_with_co_invest', models.IntegerField(blank=True, null=True, verbose_name='Цена, которая должна быть с учетом соинвеста')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Товар с Озона',
                'verbose_name_plural': 'Товары с Озон',
            },
        ),
        migrations.CreateModel(
            name='Product_from_wb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_art_from_wb', models.CharField(max_length=255, verbose_name='Артикул товара с WB')),
                ('price_with_discount_wb', models.IntegerField(blank=True, null=True, verbose_name='Цена с учетом скидки от кошелька')),
                ('wb_old_price', models.IntegerField(blank=True, null=True, verbose_name='Старая цена до скидок')),
                ('new_price_for_wb', models.IntegerField(blank=True, null=True, verbose_name='Новая цена до скидок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Товар с ВБ',
                'verbose_name_plural': 'Товары с ВБ',
            },
        ),
    ]
