# Generated by Django 5.2.6 on 2025-10-09 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст на секторе')),
                ('weight', models.PositiveIntegerField(default=1, verbose_name='Вес (вероятность)')),
                ('color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Цвет (HEX)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный сектор')),
            ],
            options={
                'verbose_name': 'Сектор колеса',
                'verbose_name_plural': 'Сектора колеса',
            },
        ),
        migrations.CreateModel(
            name='SpinResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spin_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время вращения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wheel.wheelsector', verbose_name='Выигранный сектор')),
            ],
            options={
                'verbose_name': 'Результат вращения',
                'verbose_name_plural': 'Результаты вращений',
            },
        ),
    ]
