# Generated by Django 5.2.7 on 2025-10-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cab_num', models.IntegerField(blank=True, null=True, verbose_name='Номер кабинета')),
                ('date', models.DateTimeField(verbose_name='Дата заказа')),
                ('last_change_date', models.DateTimeField(verbose_name='Дата последнего изменения')),
                ('warehouse_name', models.CharField(max_length=200, verbose_name='Название склада')),
                ('warehouse_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тип склада')),
                ('country_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна заказа')),
                ('oblast_okrug_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Округ заказа')),
                ('region_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Регион заказа')),
                ('supplier_article', models.CharField(max_length=100, verbose_name='Артикул продавца')),
                ('nm_id', models.BigIntegerField(verbose_name='Артикул WB')),
                ('subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='Наименование товара')),
                ('is_realization', models.BooleanField(default=False, verbose_name='Реализация')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'indexes': [models.Index(fields=['cab_num', 'nm_id', 'warehouse_name'], name='leftovers_o_cab_num_0e1bef_idx'), models.Index(fields=['date'], name='leftovers_o_date_e1feba_idx')],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cab_num', models.IntegerField(blank=True, null=True, verbose_name='Номер кабинета')),
                ('last_change_date', models.DateTimeField(verbose_name='Дата последнего изменения')),
                ('warehouse_name', models.CharField(max_length=200, verbose_name='Название склада')),
                ('supplier_article', models.CharField(max_length=100, verbose_name='Артикул продавца')),
                ('nm_id', models.BigIntegerField(verbose_name='Артикул WB')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('quantity_full', models.IntegerField(default=0, verbose_name='Полное количество')),
                ('subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='Наименование товара')),
            ],
            options={
                'verbose_name': 'Остаток',
                'verbose_name_plural': 'Остатки',
                'indexes': [models.Index(fields=['cab_num', 'nm_id', 'warehouse_name'], name='leftovers_s_cab_num_06cb85_idx'), models.Index(fields=['last_change_date'], name='leftovers_s_last_ch_a9d67c_idx')],
            },
        ),
    ]
