# Generated by Django 5.2.7 on 2025-10-22 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leftovers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
