# Generated by Django 5.2.5 on 2025-08-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=100, verbose_name='ID отзыва')),
                ('article_number', models.CharField(max_length=100, verbose_name='Артикул товара')),
                ('author', models.CharField(max_length=255, null=True, verbose_name='Автор')),
                ('rating', models.IntegerField(null=True, verbose_name='Рейтинг')),
                ('text', models.TextField(null=True, verbose_name='Текст отзыва')),
                ('date', models.DateTimeField(verbose_name='Дата создания отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
