# Generated by Django 5.2.6 on 2025-09-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cab_num', models.IntegerField(blank=True, null=True, verbose_name='Номер кабинета')),
                ('date', models.DateField(verbose_name='Дата')),
                ('article_number', models.CharField(max_length=100, verbose_name='Артикул товара')),
                ('avg_spp', models.FloatField(blank=True, null=True, verbose_name='Среднее значение СПП')),
                ('adv_expenses', models.IntegerField(blank=True, null=True, verbose_name='Рекламные расходы')),
                ('clicks_PK', models.IntegerField(blank=True, null=True, verbose_name='Клики по РК')),
                ('views_PK', models.IntegerField(blank=True, null=True, verbose_name='Показы по РК')),
                ('total_num_orders', models.IntegerField(blank=True, null=True, verbose_name='Общее количество заказов')),
                ('total_sum_orders', models.IntegerField(blank=True, null=True, verbose_name='Общая сумма заказов')),
                ('total_clicks', models.IntegerField(blank=True, null=True, verbose_name='Клики всего')),
                ('total_basket', models.IntegerField(blank=True, null=True, verbose_name='Корзина всего')),
                ('basket_PK', models.IntegerField(blank=True, null=True, verbose_name='Корзина из РК')),
                ('orders_num_PK', models.IntegerField(blank=True, null=True, verbose_name='Количество заказов с РК')),
                ('orders_sum_PK', models.IntegerField(blank=True, null=True, verbose_name='Сумма заказов с РК')),
                ('views_AYK', models.IntegerField(blank=True, null=True, verbose_name='АУК показы')),
                ('clicks_AYK', models.IntegerField(blank=True, null=True, verbose_name='АУК клики')),
                ('basket_AYK', models.IntegerField(blank=True, null=True, verbose_name='АУК корзина')),
                ('orders_AYK', models.IntegerField(blank=True, null=True, verbose_name='АУК заказы')),
                ('cost_AYK', models.IntegerField(blank=True, null=True, verbose_name='АУК затраты')),
                ('views_APK', models.IntegerField(blank=True, null=True, verbose_name='АРК показы')),
                ('clicks_APK', models.IntegerField(blank=True, null=True, verbose_name='АРК клики')),
                ('basket_APK', models.IntegerField(blank=True, null=True, verbose_name='АРК корзина')),
                ('orders_APK', models.IntegerField(blank=True, null=True, verbose_name='АРК заказы')),
                ('cost_APK', models.IntegerField(blank=True, null=True, verbose_name='АРК затраты')),
                ('views_rack', models.IntegerField(blank=True, null=True, verbose_name='Полки показы')),
                ('clicks_rack', models.IntegerField(blank=True, null=True, verbose_name='Полки клики')),
                ('basket_rack', models.IntegerField(blank=True, null=True, verbose_name='Полки корзина')),
                ('orders_rack', models.IntegerField(blank=True, null=True, verbose_name='Полки заказы')),
                ('cost_rack', models.IntegerField(blank=True, null=True, verbose_name='Полки затраты')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистики',
            },
        ),
    ]
