# Generated by Django 5.2.6 on 2025-09-16 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statics',
            name='basket_rack',
        ),
        migrations.RemoveField(
            model_name='statics',
            name='clicks_rack',
        ),
        migrations.RemoveField(
            model_name='statics',
            name='cost_rack',
        ),
        migrations.RemoveField(
            model_name='statics',
            name='orders_rack',
        ),
        migrations.RemoveField(
            model_name='statics',
            name='views_rack',
        ),
    ]
