# Generated by Django 5.2.6 on 2025-09-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisings', '0002_remove_statics_basket_rack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statics',
            name='buyouts_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество выкупов'),
        ),
        migrations.AddField(
            model_name='statics',
            name='buyouts_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма выкупов'),
        ),
    ]
